go_version: 1.13
version: 1.0
build_date: build_date
service:
  appname: app_api
  host: 0.0.0.0
  public_ip: 0.0.0.0
  environment: testing
http:
  host: 0.0.0.0
  port: 8101
  mode: debug

log:
  filename: /tmp/logs/app_api.log
  level: debug
  format: json
  stack: true

db:
  master:
    - data_source_name: dev:y5uCzClWa0GfiO7L@tcp(rm-2zexbx0wofppei2znoo.mysql.rds.aliyuncs.com:3306)/driver_service?parseTime=true&charset=utf8&loc=Local
      max_open_conns: 2
      max_idle_conns: 2
  slave:
    - data_source_name: dev:y5uCzClWa0GfiO7L@tcp(rm-2zexbx0wofppei2znoo.mysql.rds.aliyuncs.com:3306)/driver_service?parseTime=true&charset=utf8&loc=Local
      max_open_conns: 2
      max_idle_conns: 2

conf_cache_prefix: /guobindui.cn/houbeixiang/app_api/configuration/
etcd:
  - http://127.0.0.1:2379



#dev:y5uCzClWa0GfiO7L@tcp(rm-2zexbx0wofppei2znoo.mysql.rds.aliyuncs.com:3306)/driver_service?charset=utf8&parseTime=True&loc=Local&timeout=1000ms:
